[package]
name = "duo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.5"
clap = { version = "3", default-features = false, features = ["std", "derive"] }
duo-api = { version = "0.1", path = "../duo-api" }
parking_lot = { version = "0.12", features = ["send_guard"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3.3"
time = { version = "0.3", features = ["serde", "parsing"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
tonic = "0.8"
tower = "0.4"
tower-http = { version = "0.3", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
rand = "0.8.5"
