[package]
name = "duo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
axum = "0.5.0"
clap = { version = "3.1", default-features = false, features = [
    "std",
    "derive",
] }
duo-api = { version = "0.1", path = "../duo-api" }
parking_lot = { version = "0.12.0", features = ["send_guard"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.3.7"
tokio = { version = "1.15.0", features = ["rt-multi-thread"] }
tonic = "0.6.2"
tower = "0.4.11"
tower-http = { version = "0.2.2", features = ["fs"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.5"
