[package]
name = "duo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
arrow-array = "40"
arrow-schema = "40"
arrow-json = "40"
axum = "0.6"
rand = "0.8"
include_dir = "0.7"
clap = { version = "4", default-features = false, features = ["std", "derive"] }
duo-api = { version = "0.1", path = "../duo-api" }
duo-subscriber = { version = "0.1", path = "../duo-subscriber" }
parking_lot = { version = "0.12", features = ["send_guard"] }
parquet = { version = "40", features = ["async"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3", features = ["parsing"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
tonic = "0.9"
tower = "0.4"
tower-http = { version = "0.4", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"
datafusion = "26"

[dev-dependencies]
rstest = "0.16"
